
services: 
  sql:
    image: postgres:16
    container_name: timetables-sql
    ports:
      - 7890:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: on-failure
    logging:
      options: 
        max-size: 10m
        max-file: 3

  app:
    build: ./
    container_name: timetables-app
    ports:
      - 8080:8080
    restart: on-failure
    logging:
      options:
        max-size: 10m
        max-file: 3
    environment:
      ConnectionStrings__DefaultConnection: "Host=timetables-sql;Port=5432;Database=timeTables;Username=postgres;Password=postgres"
    depends_on:
      - sql

volumes:   
  sql-volume:
    